### ISSUE TITLE
Think about car and train rides

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/geo-activity-playground#120]
I started to also record my car and train rides. I'd be interested in seeing a heatmap with those, because these rides also contribute to my movements. But they shouldn't count towards achievements like explorer tiles or Eddington number.

**Comment by martin-ueding** [comment]
There is now the option to set it in the config like so:

```toml
[kind.Autofahrt]
consider_for_achievements = false

[kind.Bahnfahrt]
consider_for_achievements = false

[kind.Busfahrt]
consider_for_achievements = false
```

These are displayed on the heatmap, but not counted towards achievements.

Will be available in version 0.24.0.
